# Generated by Django 2.1 on 2018-11-15 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='Notice')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 11, 15, 13, 4, 16, 687182), verbose_name='date created')),
            ],
        ),
    ]
