# Generated by Django 2.1.5 on 2019-01-25 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 18, 8, 13, 93413), verbose_name='date created'),
        ),
    ]
