# Generated by Django 2.1 on 2018-11-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='student')),
                ('date_of_birth', models.DateField()),
                ('admission_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('semester', models.CharField(choices=[('F', 'First'), ('S', 'Second'), ('T', 'Third'), ('O', 'Fourth'), ('I', 'Fifth'), ('X', 'Sixth'), ('E', 'Seventh'), ('G', 'Eight')], max_length=20)),
                ('mobileno', models.IntegerField(default=20)),
            ],
        ),
    ]
