# Generated by Django 2.1 on 2018-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailabtstudent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='S', max_length=10),
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='mobileno',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='semester',
            field=models.CharField(choices=[('S', 'Select'), ('F', 'First'), ('S', 'Second'), ('T', 'Third'), ('O', 'Fourth'), ('I', 'Fifth'), ('X', 'Sixth'), ('E', 'Seventh'), ('G', 'Eight')], max_length=20),
        ),
    ]
