# Generated by Django 2.1 on 2018-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailabtstudent', '0002_auto_20181118_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='mobileno',
            field=models.IntegerField(),
        ),
    ]
