# Generated by Django 2.1 on 2018-11-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailabtstudent', '0004_auto_20181118_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='image',
            field=models.ImageField(blank=True, upload_to='Studentpic'),
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='mobileno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='semester',
            field=models.CharField(choices=[('Select', 'Select'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth')], max_length=20),
        ),
    ]
