# Generated by Django 2.1 on 2018-11-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailabtstudent', '0005_auto_20181119_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
