# Generated by Django 2.1 on 2018-11-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailabtstudent', '0007_auto_20181119_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addteachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='Teachers')),
            ],
        ),
    ]
