# Generated by Django 2.1 on 2018-11-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailabtstudent', '0008_addteachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='addteachers',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
