# Generated by Django 2.1 on 2018-11-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailabtstudent', '0009_addteachers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='S', max_length=10),
        ),
    ]
