# Generated by Django 2.1 on 2018-12-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailabtstudent', '0010_auto_20181126_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='image',
            field=models.FileField(blank=True, upload_to='detailabtstudent'),
        ),
    ]
